api/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^v1/', include('api.v1.urls', namespace='v1'))
]

apps/home/urls.py
from django.conf.urls import url


from .views import (
    index,
    loginview,
    logout_view,
    splash,
    webview,
)


urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^gig/(?P<id>[\d]+)/$', index, name="index"),
    url(r'^splash/$', splash, name="splash"),
    url(r'^login/$', loginview, name="login"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^web/$', webview, name="webview"),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('apps.home.urls', namespace="home")),

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),

    ## REST api (DRF)
    url(r'^api/', include('api.urls', namespace='api')),

    url(r'^googled647afad32a347e0.html$', TemplateView.as_view(template_name='gverify.html')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views.generic.base import TemplateView

from apps.gigs.models import Gig


class Index(TemplateView):

    template_name = 'home/index.html'

    def get(self, request, *args, **kwargs):
        #if not request.session.get('splash', False):
        #    request.session['splash'] = True
        #    return redirect('/splash/')
        return super(Index, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        gig_id = kwargs.get('id')
        if gig_id:
            context['gig_detail'] = Gig.objects.filter(pk=gig_id).first()
        return context

class WebView(TemplateView):
    template_name = 'home/web.html'


class LoginView(TemplateView):

    template_name = 'home/login.html'

class SplashView(TemplateView):

    template_name = 'home/splash.html'


def logout_view(request):
    logout(request)
    return redirect('/')



index = Index.as_view()
loginview = LoginView.as_view()
splash = SplashView.as_view()
webview = WebView.as_view()

templates/home/index.html
{% extends 'layouts/base.html' %}
{% load static from staticfiles %}


{% block content %}
{% endblock content %}

templates/home/login.html
{% extends 'layouts/base_static.html' %}
{% load static from staticfiles %}

{% block html_class %}hunnit{% endblock html_class %}
{% block body_class %}hunnit{% endblock body_class %}
{% block cont_class %}hunnit{% endblock cont_class %}

{% block navigation %}
{% endblock navigation %}

{% block content %}
<div class="login-container">
    <div class="logo">
        <a href="{% url 'home:index' %}"><img src="{% static 'images/logo.png' %}" /></a>
        <div class="maincontainer">
            <p class="tagline">For great performances and parties.</p>
        </div>
    </div>
    <div class="login-buttons">
        <a href="/accounts/facebook/login/" class="login-button facebook">Login with facebook</a>
    </div>
    <div class="login-info">
        <div class="container">
            <p>Facebook login helps see what your friends are playing or planning</p>
            <p>It also helps artists/hosts discover audience</p>
        </div>
    </div>
    <div class="login-info ics">
        <div class="row">
            <div class="six columns">
                <div class="ic"><img src="/static/images/icons/swipe.png" /></div>
                <p>To Sample Gigs</p>
            </div>
            <div class="six columns">
                <div class="ic"><img src="/static/images/icons/yellow_plus.png" /></div>
                <p>Create your own Gigs</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/home/splash.html
{% extends 'layouts/base_static.html' %}
{% load static from staticfiles %}

{% block html_class %}hunnit{% endblock html_class %}
{% block body_class %}hunnit{% endblock body_class %}
{% block cont_class %}hunnit{% endblock cont_class %}

{% block navigation %}
{% endblock navigation %}

{% block content %}
<div class="login-container splash-container">
    <div class="logo">
        <a href="{% url 'home:index' %}"><img src="{% static 'images/logo.png' %}" /></a>
        <div class="maincontainer">
            <p class="tagline">For great performances and parties.</p>
        </div>
    </div>
    <div class="login-info download-info">
        <div class="container">
            <p>Download the gigzag app here.</p>
            <a href="https://play.google.com/store/apps/details?id=com.gigs.gigzag&hl=en"><img src="{% static 'images/google.png' %}" class="download" /></a>
            <p>Or visit <a href="http://gigzag.in">GigZag.in</a> on your mobile.</p>
        </div>
    </div>
    <div class="login-info ics">
        <div class="row">
            <div class="six columns">
                <div class="ic"><img src="/static/images/icons/swipe.png" /></div>
                <p>To Sample Gigs</p>
            </div>
            <div class="six columns">
                <div class="ic"><img src="/static/images/icons/yellow_plus.png" /></div>
                <p>Create your own Gigs</p>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    setTimeout(function(){
        window.location.href = '/';
    }, 5000)
</script>
{% endblock content %}

templates/home/web.html
{% extends 'layouts/base_static.html' %}
{% load static from staticfiles %}

{% block body_class %}webview{% endblock body_class %}
{% block navigation %}{% endblock navigation %}
{% block content %}
<div class="webinfo">
    <div class="logo">
        <img src="{% static 'images/logo.png' %}" />
    </div>
    <div class="headline">
        <span class="uppercase">Discover Great Performances and parties. create your own.</span>
    </div>
    <p class="text">We built GigZag so great artists, acts and parties can find the right people, and you can get the right crowd for your own parties.</p>
    <p class="text">Try it out. And let us know! Let's change how people find events and host them!</p>
    <div class="downloads">
        <div class="row">
            <div class="six columns">
                <a href="https://play.google.com/store/apps/details?id=com.gigs.gigzag&hl=en"><img src="{% static 'images/google.png' %}" /></a>
                <div>Download the gigzag android app</div>
            </div>
            <div class="six columns">
                <div class="title">GigZag.in</div>
                <div>Visit the GigZag mobile site</div>
            </div>
        </div>
    </div>
    <div class="social">
        <a href="https://facebook.com/GigZagMe">
            <img src="{% static 'images/social_facebook.png' %}" />
        </a>
        <a href="https://twitter.com/GigZagMe">
            <img src="{% static 'images/social_twitter.png' %}" />
        </a>
        <a href="https://instagram.com/GigZagMe">
            <img src="{% static 'images/social_instagram.png' %}" />
        </a>
    </div>
    <div class="contact">
        <a href="mailto:contact@gigzag.in">Contact</a>  |
        <a href="mailto:feedback@gigzag.in">Feedback</a>
    </div>
</div>
{% endblock content %}